# Generated by Django 2.0.2 on 2018-02-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180212_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='year_of_birth',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='year_of_death',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_of_publication',
            field=models.CharField(max_length=50),
        ),
    ]
