# Generated by Django 2.0.2 on 2018-02-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20180212_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='alternate_names',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
