# Generated by Django 2.0.2 on 2018-02-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20180213_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('ol_id', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='year_of_birth',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='year_of_death',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_of_publication',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='work',
            name='authors',
            field=models.ManyToManyField(to='base.Author'),
        ),
    ]
