# Generated by Django 2.0.2 on 2018-02-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20180216_0751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='author',
            name='alternate_names',
            field=models.CharField(blank=True, db_index=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(choices=[('AP', 'ANDHRA PRADESH'), ('AR', 'ARUNACHAL PRADESH'), ('AS', 'ASSAM'), ('BR', 'BIHAR'), ('CG', 'CHATTISGARH'), ('DL', 'DELHI'), ('GA', 'GOA'), ('GJ', 'GUJARAT'), ('HR', 'HARYANA'), ('HP', 'HIMACHAL PRADESH'), ('JK', 'JAMMU & KASHMIR'), ('JS', 'JHARKHAND'), ('KA', 'KARNATAKA'), ('MP', 'MADHYA PRADESH'), ('MH', 'MAHARASHTRA'), ('MN', 'MANIPUR'), ('ML', 'MEGHALAYA'), ('MZ', 'MIZORAM'), ('NL', 'NAGALAND'), ('OR', 'ORISSA'), ('PB', 'PUNJAB'), ('RJ', 'RAJASTHAN'), ('SK', 'SIKKIM'), ('TN', 'TAMIL NADU'), ('TR', 'TRIPURA'), ('UK', 'UTTARAKHAND'), ('UP', 'UTTAR PRADESH'), ('WB', 'WEST BENGAL'), ('AN', 'ANDAMAN & NICOBAR'), ('CH', 'CHANDIGARH'), ('DN', 'DADAR & NAGAR HAVELI'), ('DD', 'DAMAN & DIU'), ('LD', 'LAKSHADWEEP'), ('PY', 'PONDICHERRY')], db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(db_index=True, max_length=1024),
        ),
    ]
