# Generated by Django 2.0.2 on 2018-02-27 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_auto_20180219_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'boxes',
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='box',
            name='books',
            field=models.ManyToManyField(to='base.Book'),
        ),
        migrations.AddField(
            model_name='box',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Payment'),
        ),
        migrations.AddField(
            model_name='box',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
