# Generated by Django 2.0.2 on 2018-02-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
