# Generated by Django 2.0.2 on 2018-03-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20180227_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='tracking_code',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
